### ISSUE TITLE
Something is wrong when  "normalize_factors" is set True

### ISSUE THREAD

**Issue by lingzenan** [tensorly/tensorly#116]
When I ran the following code:

X = tl.tensor(np.random.randn(8,8,8)/ 8 )
weights, factors = parafac(X, rank=2, normalize_factors=True)

I got this error:

Traceback (most recent call last):
  File "/home/lingzenan/文档/new_iresnet/tensor.py", line 6, in <module>
    weights, factors = candecomp_parafac.parafac(X, rank=2, init='svd',normalize_factors=True)
  File "/home/lingzenan/tensorly/tensorly/decomposition/candecomp_parafac.py", line 188, in parafac
    factor = tl.transpose(tl.solve(tl.conj(tl.transpose(pseudo_inverse)), tl.transpose(mttkrp)))
  File "/home/lingzenan/tensorly/tensorly/backend/__init__.py", line 160, in inner
    return _get_backend_method(name)(*args, **kwargs)
  File "/home/lingzenan/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 390, in solve
    r = gufunc(a, b, signature=signature, extobj=extobj)
  File "/home/lingzenan/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 89, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.linalg.LinAlgError: Singular matrix

I haven't found the solution yet. Can you help me?

**Comment by JeanKossaifi** [comment]
Thanks for reporting. I am not sure why this occurs, will look into it as soon as I get a second.
Let me know if you find anything in the meantime!

**Comment by JeanKossaifi** [comment]
Hi @lingzenan 
Thanks for noticing and reporting the issue. 
It should now be fixed in master.
Please feel free to reopen if this does not fix your issue.
