### ISSUE TITLE
Partial_tucker method issue in tensorly 0.5.1

### ISSUE THREAD

**Issue by andrejchenko** [tensorly/tensorly#241]
Hi there,

I've noticed that with the new version of tensorly: 0.5.1 I receive an error when I call the ```partial_tucker``` method.
Here is the traceback I have:

```
UserWarning: In partial_svd: converting to NumPy. Check SVD_FUNS for available alternatives if you want to avoid this.
  warnings.warn('In partial_svd: converting to NumPy.'
Traceback (most recent call last):
  File ".../lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File ".../lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
 ...
File "/test.py", line 60, in <module>
    main()  
    core, factors = partial_tucker(tensor, modes, my_ranks, init='svd' )
  File ".../tensorly/decomposition/_tucker.py", line 84, in partial_tucker
    eigenvecs, _, _ = svd_fun(unfold(tensor, mode), n_eigenvecs=rank[index], random_state=random_state)
  File ".../tensorly/backend/core.py", line 841, in partial_svd
    U, S, V = scipy.linalg.svd(matrix, full_matrices=True)
  File ".../.conda/envs/.../lib/python3.8/site-packages/scipy/linalg/decomp_svd.py", line 125, in svd
    u, s, v, info = gesXd(a1, compute_uv=compute_uv, lwork=lwork,
numpy.core._exceptions.MemoryError: Unable to allocate 44.6 PiB for an array with shape (112000000, 112000000) and data type float32
```
I use a conda environment ```(setup1)``` where I have: pytorch=1.8.0, python=3.8.5 & cuda 11.2.

An error will occur also with this environment ```(setup2)```: pytorch=1.7.1, python=3.6 & cuda 10.2:

```
In partial_svd: converting to NumPy. Check SVD_FUNS for available alternatives if you want to avoid this.
  warnings.warn('In partial_svd: converting to NumPy.'
/.../tensorly/backend/core.py:854: RuntimeWarning: invalid value encountered in sqrt
  S = np.where(np.abs(S) <= np.finfo(S.dtype).eps, 0, np.sqrt(S))
Traceback (most recent call last):
  File ".../lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File ".../lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
...
  File "/test.py", line 60, in <module>
    main()  
    core, factors = partial_tucker(tensor, modes, my_ranks, init='random', mask = mask_tensor )
  File ".../tensorly/tensorly/decomposition/_tucker.py", line 109, in partial_tucker
    eigenvecs, _, _ = svd_fun(unfold(core_approximation, mode), n_eigenvecs=rank[index], random_state=random_state)
  File ".../tensorly/backend/core.py", line 841, in partial_svd
    U, S, V = scipy.linalg.svd(matrix, full_matrices=True)
  File "/app/conda/envs/<...>/lib/python3.6/site-packages/scipy/linalg/decomp_svd.py", line 125, in svd
    compute_uv=compute_uv, full_matrices=full_matrices)
  File "/app/conda/envs/<...>/lib/python3.6/site-packages/scipy/linalg/lapack.py", line 812, in _compute_lwork
    return _check_work_float(ret[0].real, dtype)
  File "/app/conda/envs/<...>/lib/python3.6/site-packages/scipy/linalg/lapack.py", line 830, in _check_work_float
    raise ValueError("Too large work array required -- computation cannot "
ValueError: Too large work array required -- computation cannot be performed with standard 32-bit LAPACK.
```
In both cases it seems that the issue comes from the ```svd``` method.
 
Hence,  the masking option from ```partial_tucker```  also fails:
```core, factors = partial_tucker(tensor, modes, my_ranks , init='random', mask = mask_tensor )```

Before I used the ```tensorly=0.4.6``` with the ```setup2``` having no issues when I called the ```partial_tucker``` method:
```core, factors = partial_tucker(tensor, modes, my_ranks , init='svd' )```

Code for reproducing the above mentioned error with ```tensorly=0.5.1```:

```import numpy as np
from numpy import save
import pandas as pd
import math
import tensorly as tl
from tensorly import unfold
from tensorly.tucker_tensor import tucker_to_tensor
from tensorly.decomposition import tucker
from tensorly.decomposition import partial_tucker
from tensorly import tenalg

def main():
    tl.set_backend('pytorch')
    x_orig = np.random.rand(80000, 1400,4)
    x = x_orig
    masks = []
    for slice in  range(x.shape[2]):
        print(x[:,:,slice].shape)
        mask = np.ones(x[:,:,slice].shape)
        num_miss_rows = 1000
        rand_rows       = np.random.randint(x.shape[0], size=(num_miss_rows))
        mask[rand_rows,:] = 0
        print(np.isnan(x).any())
        x[rand_rows,:,slice] = 0 
        print(np.isnan(x).any())
        masks.append(mask)
    mask_patterns = np.stack(masks, axis = 2)
    print(mask_patterns.shape)

    tensor      = tl.tensor(x, device = 'cpu')
    mask_tensor = tl.tensor(mask_patterns, device = 'cpu')

    my_ranks = [1000, 4]
    modes= [1,2]

    core, factors = partial_tucker(tensor, modes, my_ranks , init='svd' )
    core, factors = partial_tucker(tensor, modes, my_ranks , init='random', mask = mask_tensor )

if __name__ == "__main__":
    main() ```

**Comment by JeanKossaifi** [comment]
Thanks for reporting @andrejchenko!

It turns out it was some small change in `partial_svd`: using full_matrices makes things very slow so we shouldn't use it when `n_eigenvecs == min(matrix.shape)`. 

This is fixed by 0a7faea35ba9b067d469fb24f081ea431727587c and I've added a test for that case in 244c94b0533172c4ee223305b6a6dad4c53a3422.
