### ISSUE TITLE
Error when running sparse Robust PCA

### ISSUE THREAD

**Issue by dawe** [tensorly/tensorly#499]
#### Describe the bug
Computation of sparse robust pca crashes as it calls svd with unexpected keyword (`full_matrices`)

#### Steps or Code to Reproduce
Mostly copied from tensorly docs
```python
import tensorly.contrib.sparse as stl; import sparse
shape = (1000, 1001, 1002)
rank = 5
starting_weights = stl.ones((rank))
starting_factors = [sparse.random((i, rank)) for i in shape]
from tensorly.contrib.sparse.cp_tensor import cp_to_tensor
tensor = cp_to_tensor((starting_weights, starting_factors))
from tensorly.decomposition import robust_pca
from tensorly.contrib.sparse.decomposition import robust_pca as  sparse_robust_pca
dense_tensor = tensor.todense()
d_RPCA = robust_pca(dense_tensor)
s_RPCA = sparse_robust_pca(tensor)
```

#### Expected behavior
Should compute s_RPCA (equal to d_RPCA)

#### Actual result

```ptyhon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cittaro.davide/miniforge3/envs/sep22/lib/python3.9/site-packages/tensorly/contrib/sparse/core.py", line 12, in inner
    return func(*args, **kwargs)
  File "/home/cittaro.davide/miniforge3/envs/sep22/lib/python3.9/site-packages/tensorly/decomposition/robust_decomposition.py", line 112, in robust_pca
    svd_thresholding(unfold(D, i) + unfold(L[i], i) / mu, reg_J / mu),
  File "/home/cittaro.davide/miniforge3/envs/sep22/lib/python3.9/site-packages/tensorly/tenalg/proximal.py", line 845, in svd_thresholding
    U, s, V = tl.truncated_svd(matrix, n_eigenvecs=min(matrix.shape))
  File "/home/cittaro.davide/miniforge3/envs/sep22/lib/python3.9/site-packages/tensorly/tenalg/svd.py", line 226, in truncated_svd
    U, S, V = tl.svd(matrix, full_matrices=full_matrices)
  File "/home/cittaro.davide/miniforge3/envs/sep22/lib/python3.9/site-packages/tensorly/backend/__init__.py", line 206, in wrapped_backend_method
    return getattr(
TypeError: svd() got an unexpected keyword argument 'full_matrices'
```

#### Versions

```python
>>> import platform; print(platform.platform())
Linux-3.10.0-1127.el7.x86_64-x86_64-with-glibc2.17
>>> import sys; print("Python", sys.version)
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21) 
[GCC 10.3.0]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.23.5
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.9.1
>>> import tensorly; print("TensorLy", tensorly.__version__)
TensorLy 0.8.1
```

**Comment by aarmey** [comment]
Thanks for reporting this @dawe.

@JeanKossaifi, because [this skip line](https://github.com/tensorly/tensorly/blob/e45c97eda738799e779b09b654e1422f775f08ea/tensorly/contrib/sparse/tests/test_decomposition.py#L10) is not indented within the if statement above, the sparse tests are always skipped. I assume this should be moved within the if statement?

**Comment by aarmey** [comment]
Some information I found:

- This is not actually an error with the `full_matrices` option. The actual error when you remove dynamic dispatch is that no `svd` method exists for `COO` matrices.
- The error appears this way because we need to add the `full_matrices` option to the stub in `backend/core.py` to match the real function signatures.
- One broader issue here is that `svd_thresholding()` needs to avoid calling `tl.truncated_svd()` in the first place, because it is not setup for sparse matrices.
- If this will be an option within `svd_thresholding()`, then we would need to expose it in `robust_pca()`. Adding an option for the SVD method is probably best so that the user can adjust this for performance, too.
- There still exists the issue with testing, I believe.

**Comment by JeanKossaifi** [comment]
Thanks for opening @dawe and thanks for digging into it @aarmey!

Regarding the testing, it should only be skipped if sparse is not installed - that should never be an issue for us (we can double check we indeed install pydata-sparse) but avoids test failures if users run the test suite locally without it installed. 

[`pytest.importorskip`](https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest-importorskip) only skips if import fails:
```
Import and return the requested module modname, or skip the current test if the module cannot be imported.
```

We haven't updated the sparse backend for a while and indeed quite likely the interfaces no longer match and should be updated.

**Comment by JeanKossaifi** [comment]
@dawe would you be interested in opening a small PR to fix the issue?

**Comment by ghbrown** [comment]
The same error seems to plague `tensorly.contrib.sparse.decomposition.parafac`.

**Comment by lwelzel** [comment]
I am encountering the same issue with the sparse Tucker decomposition in tensorly.contrib.sparse.decomposition:

```python
import numpy as np
import tensorly.contrib.sparse.decomposition as tld

# make tensor and mask
tensor = np.arange(int(10**4)).reshape((10, 10, 10, 10))

mask = np.ones_like(tensor)
mask[-3:-1] = 0.

# try to find the tucker decomposition
core, tucker_factors = tld.tucker( # <- fails here
    tensor,
    mask=mask,
    rank=[2, 2, 2, 2]
)

tensor_model = tl.tucker_to_tensor((core, tucker_factors))
```

As @aarmey pointed out, the actual underlying issue is that none of the svd methods in the svd_interface support sparse tensors. From what I understand the decompositions of sparse tensors are only supported on numpy arrays. 

Is there a way to still use the sparse decompositions, e.g. by explicitly passing sparse svd methods (scipy.sparse.linalg.svds or cupyx.scipy.sparse.linalg.svds)?

Any advice would be very much appreciated!

**Comment by aarmey** [comment]
It should be straightforward to make `randomized_svd()` and `symeig_svd()` sparse safe, as they only work with products of the sparse tensor. However, I am interested in Jean's input as I haven't worked with the sparse backend.
