### ISSUE TITLE
Errors happened when resetting backend

### ISSUE THREAD

**Issue by JianboGuo** [tensorly/tensorly#8]
I used the following official code to set backend for tensorly lib:
`tl.set_backend('numpy')`
and suffered from errors:
`AttributeError: 'module' object has no attribute 'reload'
`
Actually I find importlib doesn't have reload function. How can I solve this problem? I would appreciate you kind reply.

**Comment by JianboGuo** [comment]
@animakumar  @JeanKossaifi I am using Python 2.7+ and I found it's because there was no 'reload' func in importlib module in this series of versions. However, I used another method mentioned in your docs
`# Set the default backend
default_backend = 'numpy'`
and suffered from
`Using numpy backend.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Jianbo/Programs/anaconda2/lib/python2.7/site-packages/tensorly/__init__.py", line 28, in <module>
    from .backend import *
  File "/Users/Jianbo/Programs/anaconda2/lib/python2.7/site-packages/tensorly/backend/__init__.py", line 9, in <module>
    from .numpy_backend import *
  File "/Users/Jianbo/Programs/anaconda2/lib/python2.7/site-packages/tensorly/backend/numpy_backend.py", line 5, in <module>
    from numpy import testing
  File "/Users/Jianbo/Programs/anaconda2/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/Users/Jianbo/Programs/anaconda2/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/Users/Jianbo/Programs/anaconda2/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/Users/Jianbo/Programs/anaconda2/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/Users/Jianbo/Programs/anaconda2/lib/python2.7/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.`

How can I change the backend to numpy since I need to transfer the mxnet NDarray type in Tensorly into the numpy array type after CPD?

**Comment by JeanKossaifi** [comment]
TensorLy is only developed for python 3: updating to Python 3.5 or higher should fix your error.
